# Generated by Django 5.0.6 on 2024-06-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPrueba', '0003_rename_title_musica_name_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('birthdate', models.CharField(max_length=30)),
                ('important_albums', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=25)),
                ('number_series', models.IntegerField()),
            ],
        ),
    ]
