# Generated by Django 5.0.6 on 2024-06-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPrueba', '0009_delete_instrumento_remove_producto_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marca', models.CharField(default='Sin marca', max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='instrumentos/')),
                ('fecha_fabricacion', models.DateField()),
                ('en_stock', models.BooleanField(default=True)),
                ('peso', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
