# Generated by Django 5.0.6 on 2024-06-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPrueba', '0010_instrumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInstrumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='en_stock',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='fecha_fabricacion',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='peso',
        ),
        migrations.AddField(
            model_name='instrumento',
            name='cantidad_disponible',
            field=models.IntegerField(default=0),
        ),
    ]
