# Generated by Django 5.0.6 on 2024-06-24 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPrueba', '0011_categoriainstrumentos_remove_instrumento_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrumento',
            old_name='tipo',
            new_name='modelo',
        ),
    ]
