# Generated by Django 5.0.6 on 2024-06-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPrueba', '0015_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
