# Generated by Django 5.0.6 on 2024-06-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPrueba', '0017_artista_biografia_artista_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.AddField(
            model_name='instrumento',
            name='tipo',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
