# Generated by Django 5.0.6 on 2024-06-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPrueba', '0018_remove_pedido_producto_remove_pedido_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumento',
            name='tipo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
