# Generated by Django 5.0.6 on 2024-06-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPrueba', '0019_alter_instrumento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumento',
            name='tipo',
            field=models.CharField(choices=[('guitarra', 'Guitarra'), ('bajo', 'Bajo'), ('baterias', 'Baterias'), ('violines', 'Violines'), ('ukeleles', 'Ukeleles'), ('saxofones', 'Saxofones'), ('pianos', 'Pianos'), ('acordeones', 'Acordeones'), ('flautas', 'Flautas')], default='', max_length=50),
        ),
    ]
