# Generated by Django 5.0.6 on 2024-07-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPrueba', '0021_carrito_itemcarrito_carrito_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumento',
            name='marca',
            field=models.CharField(default='', max_length=50),
        ),
    ]
